version: '3.8'
services:
  db:
    image: bigpapoo/r408-mysql:5.7
    container_name: fittracker_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=fittracker
      - MYSQL_USER=fituser
      - MYSQL_PASSWORD=fitpass
    volumes:
      - mysql_vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - rezo_fittracker

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fittracker_web
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./assets:/var/www/assets
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: fittracker
      DB_USER: fituser
      DB_PASSWORD: fitpass
    networks:
      - rezo_fittracker

  pma:
    image: bigpapoo/r408-phpmyadmin:5.2
    container_name: fittracker_pma
    restart: unless-stopped
    ports:
      - "8060:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - rezo_fittracker

networks:
  rezo_fittracker:

volumes:
  mysql_vol: